spring:
  datasource:
    url: jdbc:mysql://localhost:3306/predix?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: root00!@

  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/
    suffix: .html
    mode: HTML

  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
      show-sql: true
      properties: # JPA 공급자 (Hibernate)에 전달할 추가 속성
        hibernate:
          format_sql: true # SQL 쿼리를 보기 좋게 포맷팅
jwt:
  secret: "${JWT_SECRET:your-very-long-and-secure-secret-key-that-is-at-least-sixty-four-characters-long-for-HS512-algorithm-security-purposes-and-must-be-randomly-generated-and-kept-secret-do-not-use-this-example-key-in-production-ever-it-is-just-for-demonstration}"
  access-ttl: 900000
  refresh-ttl: 2592000000

server:
  port: 8443
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: 123456
    key-store-type: PKCS12
    key-alias: predix-ssl
    client-auth: none

logging:
  level:
#    root: DEBUG
    org:
      thymeleaf:
#        TemplateEngine: TRACE
      springframework:
#        security: DEBUG
      apache:
        tomcat:
          util:
            net:
              jsse: INFO

weather:
  kma:
    base-url: https://apis.data.go.kr/1360000/AsosDalyInfoService/getWthrDataList
    service-key:
